/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_c_b_gestion_coach_coach (void)
{
  GtkWidget *c_b_gestion_coach_coach;
  GtkWidget *fixed1;
  GtkWidget *notebook1;
  GtkWidget *fixed2;
  GtkWidget *entry1_id;
  GtkWidget *entry2_md;
  GtkWidget *image3;
  GtkWidget *image4;
  GtkWidget *image5;
  GtkWidget *image6;
  GtkWidget *label6_id;
  GtkWidget *label7_md;
  GtkWidget *image10;
  GtkWidget *image7;
  GtkWidget *image9;
  GtkWidget *image15;
  GtkWidget *button2_valider;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label8;
  GtkWidget *button1_mdo;
  GtkWidget *image8;
  GtkWidget *label_acc;
  GtkWidget *label_acceuil;
  GtkWidget *fixed3;
  GtkWidget *treeview1;
  GtkWidget *label10;
  GtkWidget *button4_sinsc;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label11;
  GtkWidget *image13;
  GtkWidget *image14;
  GtkWidget *image62;
  GtkWidget *image12;
  GtkWidget *labelcal;
  GtkWidget *label2_lis_c;
  GtkWidget *fixed4;
  GtkWidget *image57;
  GtkWidget *image59;
  GtkWidget *image63;
  GtkWidget *image65;
  GtkWidget *entryquantit___equipm_reserver;
  GtkObject *spinbutton_jour_adj;
  GtkWidget *spinbutton_jour;
  GtkObject *spinbuttonmois_adj;
  GtkWidget *spinbuttonmois;
  GtkObject *spinbutton_anne_adj;
  GtkWidget *spinbutton_anne;
  GtkObject *spinbutton6_adj;
  GtkWidget *spinbutton6;
  GtkObject *spinbutton7_adj;
  GtkWidget *spinbutton7;
  GtkWidget *buttonreserver_coach_equipm;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image67;
  GtkWidget *label60;
  GtkWidget *label57;
  GtkWidget *label58;
  GtkWidget *label59;
  GtkWidget *label54;
  GtkWidget *label55;
  GtkWidget *label56;
  GtkWidget *label53;
  GtkWidget *label52;
  GtkWidget *combobox__quipmentC;
  GtkWidget *reserver___quipment_c;
  GtkWidget *fixed14;
  GtkWidget *image58;
  GtkWidget *fixed15;
  GtkWidget *image60;
  GtkWidget *image61;
  GtkWidget *image64;
  GtkWidget *image66;
  GtkWidget *label51;
  GtkWidget *s_inscrire_cours;
  GtkWidget *coach_reserver_equipm;
  GtkWidget *acceuil1;

  c_b_gestion_coach_coach = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (c_b_gestion_coach_coach), _("c_b_grstion coach.coach"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (c_b_gestion_coach_coach), fixed1);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_fixed_put (GTK_FIXED (fixed1), notebook1, 0, 0);
  gtk_widget_set_size_request (notebook1, 1288, 640);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed2);

  entry1_id = gtk_entry_new ();
  gtk_widget_show (entry1_id);
  gtk_fixed_put (GTK_FIXED (fixed2), entry1_id, 504, 272);
  gtk_widget_set_size_request (entry1_id, 216, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1_id), 8226);

  entry2_md = gtk_entry_new ();
  gtk_widget_show (entry2_md);
  gtk_fixed_put (GTK_FIXED (fixed2), entry2_md, 504, 360);
  gtk_widget_set_size_request (entry2_md, 216, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2_md), 8226);

  image3 = create_pixmap (c_b_gestion_coach_coach, "551044963_789941773825632_1486066102389035571_n.png");
  gtk_widget_show (image3);
  gtk_fixed_put (GTK_FIXED (fixed2), image3, 1128, 0);
  gtk_widget_set_size_request (image3, 160, 408);

  image4 = create_pixmap (c_b_gestion_coach_coach, "551044963_789941773825632_1486066102389035571_n.png");
  gtk_widget_show (image4);
  gtk_fixed_put (GTK_FIXED (fixed2), image4, 1128, 0);
  gtk_widget_set_size_request (image4, 160, 408);

  image5 = create_pixmap (c_b_gestion_coach_coach, "551044963_789941773825632_1486066102389035571_n.png");
  gtk_widget_show (image5);
  gtk_fixed_put (GTK_FIXED (fixed2), image5, 1128, 0);
  gtk_widget_set_size_request (image5, 160, 408);

  image6 = create_pixmap (c_b_gestion_coach_coach, "551044963_789941773825632_1486066102389035571_n.png");
  gtk_widget_show (image6);
  gtk_fixed_put (GTK_FIXED (fixed2), image6, 1128, 0);
  gtk_widget_set_size_request (image6, 160, 408);

  label6_id = gtk_label_new (_("ENTRER VOTRE ID "));
  gtk_widget_show (label6_id);
  gtk_fixed_put (GTK_FIXED (fixed2), label6_id, 488, 232);
  gtk_widget_set_size_request (label6_id, 240, 48);

  label7_md = gtk_label_new (_(" ENTRER VOTRE MOT DE PASSE"));
  gtk_widget_show (label7_md);
  gtk_fixed_put (GTK_FIXED (fixed2), label7_md, 480, 328);
  gtk_widget_set_size_request (label7_md, 256, 32);

  image10 = create_pixmap (c_b_gestion_coach_coach, "553285991_4122503948018201_4707852305121133389_n.png");
  gtk_widget_show (image10);
  gtk_fixed_put (GTK_FIXED (fixed2), image10, 0, 400);
  gtk_widget_set_size_request (image10, 128, 224);

  image7 = create_pixmap (c_b_gestion_coach_coach, "551044963_789941773825632_1486066102389035571_n.png");
  gtk_widget_show (image7);
  gtk_fixed_put (GTK_FIXED (fixed2), image7, 1128, 400);
  gtk_widget_set_size_request (image7, 160, 216);

  image9 = create_pixmap (c_b_gestion_coach_coach, "553285991_4122503948018201_4707852305121133389_n.png");
  gtk_widget_show (image9);
  gtk_fixed_put (GTK_FIXED (fixed2), image9, 0, 0);
  gtk_widget_set_size_request (image9, 128, 408);

  image15 = create_pixmap (c_b_gestion_coach_coach, "553285991_4122503948018201_4707852305121133389_n.png");
  gtk_widget_show (image15);
  gtk_fixed_put (GTK_FIXED (fixed2), image15, 0, 400);
  gtk_widget_set_size_request (image15, 128, 224);

  button2_valider = gtk_button_new ();
  gtk_widget_show (button2_valider);
  gtk_fixed_put (GTK_FIXED (fixed2), button2_valider, 528, 488);
  gtk_widget_set_size_request (button2_valider, 160, 56);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (button2_valider), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label8 = gtk_label_new_with_mnemonic (_("Valider"));
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (hbox1), label8, FALSE, FALSE, 0);

  button1_mdo = gtk_button_new_with_mnemonic (_("MOT DE PASSE OUBLIE ?"));
  gtk_widget_show (button1_mdo);
  gtk_fixed_put (GTK_FIXED (fixed2), button1_mdo, 504, 408);
  gtk_widget_set_size_request (button1_mdo, 224, 40);

  image8 = create_pixmap (c_b_gestion_coach_coach, "551044963_789941773825632_1486066102389035571_n.png");
  gtk_widget_show (image8);
  gtk_fixed_put (GTK_FIXED (fixed2), image8, 1128, 0);
  gtk_widget_set_size_request (image8, 160, 408);

  label_acc = gtk_label_new (_("<span foreground=\"green\"font_desc=\"Arial 30\">BIENVENUE A SPRIFIT !\nVEULLEZ ENTRER VOS DONNEES </span>"));
  gtk_widget_show (label_acc);
  gtk_fixed_put (GTK_FIXED (fixed2), label_acc, 240, 24);
  gtk_widget_set_size_request (label_acc, 792, 176);
  gtk_label_set_use_markup (GTK_LABEL (label_acc), TRUE);
  gtk_label_set_justify (GTK_LABEL (label_acc), GTK_JUSTIFY_CENTER);

  label_acceuil = gtk_label_new (_("Acceuil"));
  gtk_widget_show (label_acceuil);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label_acceuil);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed3);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed3), treeview1, 456, 224);
  gtk_widget_set_size_request (treeview1, 300, 200);

  label10 = gtk_label_new (_("<span foreground=\"green\"font_desc=\"Arial 25\"> VEUILLEZ SELECTIONNEZ \nLE(S) COURS A REJOINDRE </span>"));
  gtk_widget_show (label10);
  gtk_fixed_put (GTK_FIXED (fixed3), label10, 280, 24);
  gtk_widget_set_size_request (label10, 656, 168);
  gtk_label_set_use_markup (GTK_LABEL (label10), TRUE);

  button4_sinsc = gtk_button_new ();
  gtk_widget_show (button4_sinsc);
  gtk_fixed_put (GTK_FIXED (fixed3), button4_sinsc, 504, 472);
  gtk_widget_set_size_request (button4_sinsc, 176, 56);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button4_sinsc), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label11 = gtk_label_new_with_mnemonic (_("S'inscrire"));
  gtk_widget_show (label11);
  gtk_box_pack_start (GTK_BOX (hbox2), label11, FALSE, FALSE, 0);

  image13 = create_pixmap (c_b_gestion_coach_coach, "553285991_4122503948018201_4707852305121133389_n.png");
  gtk_widget_show (image13);
  gtk_fixed_put (GTK_FIXED (fixed3), image13, 0, 0);
  gtk_widget_set_size_request (image13, 128, 408);

  image14 = create_pixmap (c_b_gestion_coach_coach, "553285991_4122503948018201_4707852305121133389_n.png");
  gtk_widget_show (image14);
  gtk_fixed_put (GTK_FIXED (fixed3), image14, 0, 400);
  gtk_widget_set_size_request (image14, 128, 224);

  image62 = create_pixmap (c_b_gestion_coach_coach, "551044963_789941773825632_1486066102389035571_n.png");
  gtk_widget_show (image62);
  gtk_fixed_put (GTK_FIXED (fixed3), image62, 1128, 0);
  gtk_widget_set_size_request (image62, 160, 408);

  image12 = create_pixmap (c_b_gestion_coach_coach, "551044963_789941773825632_1486066102389035571_n.png");
  gtk_widget_show (image12);
  gtk_fixed_put (GTK_FIXED (fixed3), image12, 1128, 400);
  gtk_widget_set_size_request (image12, 160, 216);

  labelcal = gtk_label_new ("");
  gtk_widget_show (labelcal);
  gtk_fixed_put (GTK_FIXED (fixed3), labelcal, 368, 528);
  gtk_widget_set_size_request (labelcal, 456, 56);

  label2_lis_c = gtk_label_new (_("Liste des cours"));
  gtk_widget_show (label2_lis_c);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label2_lis_c);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed4);

  image57 = create_pixmap (c_b_gestion_coach_coach, "553285991_4122503948018201_4707852305121133389_n.png");
  gtk_widget_show (image57);
  gtk_fixed_put (GTK_FIXED (fixed4), image57, 0, 0);
  gtk_widget_set_size_request (image57, 128, 408);

  image59 = create_pixmap (c_b_gestion_coach_coach, "553285991_4122503948018201_4707852305121133389_n.png");
  gtk_widget_show (image59);
  gtk_fixed_put (GTK_FIXED (fixed4), image59, 0, 400);
  gtk_widget_set_size_request (image59, 128, 224);

  image63 = create_pixmap (c_b_gestion_coach_coach, "551044963_789941773825632_1486066102389035571_n.png");
  gtk_widget_show (image63);
  gtk_fixed_put (GTK_FIXED (fixed4), image63, 1128, 0);
  gtk_widget_set_size_request (image63, 160, 408);

  image65 = create_pixmap (c_b_gestion_coach_coach, "551044963_789941773825632_1486066102389035571_n.png");
  gtk_widget_show (image65);
  gtk_fixed_put (GTK_FIXED (fixed4), image65, 1128, 400);
  gtk_widget_set_size_request (image65, 160, 216);

  entryquantit___equipm_reserver = gtk_entry_new ();
  gtk_widget_show (entryquantit___equipm_reserver);
  gtk_fixed_put (GTK_FIXED (fixed4), entryquantit___equipm_reserver, 600, 184);
  gtk_widget_set_size_request (entryquantit___equipm_reserver, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryquantit___equipm_reserver), 8226);

  spinbutton_jour_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  spinbutton_jour = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_jour_adj), 1, 0);
  gtk_widget_show (spinbutton_jour);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbutton_jour, 608, 240);
  gtk_widget_set_size_request (spinbutton_jour, 60, 27);

  spinbuttonmois_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinbuttonmois = gtk_spin_button_new (GTK_ADJUSTMENT (spinbuttonmois_adj), 1, 0);
  gtk_widget_show (spinbuttonmois);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbuttonmois, 720, 240);
  gtk_widget_set_size_request (spinbuttonmois, 60, 24);

  spinbutton_anne_adj = gtk_adjustment_new (2025, 2025, 2030, 1, 10, 10);
  spinbutton_anne = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_anne_adj), 1, 0);
  gtk_widget_show (spinbutton_anne);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbutton_anne, 824, 240);
  gtk_widget_set_size_request (spinbutton_anne, 60, 27);

  spinbutton6_adj = gtk_adjustment_new (1, 1, 24, 1, 10, 10);
  spinbutton6 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton6_adj), 1, 0);
  gtk_widget_show (spinbutton6);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbutton6, 608, 296);
  gtk_widget_set_size_request (spinbutton6, 60, 27);

  spinbutton7_adj = gtk_adjustment_new (1, 1, 59, 1, 10, 10);
  spinbutton7 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton7_adj), 1, 0);
  gtk_widget_show (spinbutton7);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbutton7, 744, 296);
  gtk_widget_set_size_request (spinbutton7, 60, 27);

  buttonreserver_coach_equipm = gtk_button_new ();
  gtk_widget_show (buttonreserver_coach_equipm);
  gtk_fixed_put (GTK_FIXED (fixed4), buttonreserver_coach_equipm, 560, 472);
  gtk_widget_set_size_request (buttonreserver_coach_equipm, 192, 72);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (buttonreserver_coach_equipm), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image67 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image67);
  gtk_box_pack_start (GTK_BOX (hbox12), image67, FALSE, FALSE, 0);

  label60 = gtk_label_new_with_mnemonic (_("reserver"));
  gtk_widget_show (label60);
  gtk_box_pack_start (GTK_BOX (hbox12), label60, FALSE, FALSE, 0);

  label57 = gtk_label_new (_("Dur\303\251e du cours :"));
  gtk_widget_show (label57);
  gtk_fixed_put (GTK_FIXED (fixed4), label57, 416, 288);
  gtk_widget_set_size_request (label57, 128, 40);

  label58 = gtk_label_new (_("hr"));
  gtk_widget_show (label58);
  gtk_fixed_put (GTK_FIXED (fixed4), label58, 672, 296);
  gtk_widget_set_size_request (label58, 56, 24);

  label59 = gtk_label_new (_("min"));
  gtk_widget_show (label59);
  gtk_fixed_put (GTK_FIXED (fixed4), label59, 816, 296);
  gtk_widget_set_size_request (label59, 48, 25);

  label54 = gtk_label_new (_("Date du cours :"));
  gtk_widget_show (label54);
  gtk_fixed_put (GTK_FIXED (fixed4), label54, 416, 240);
  gtk_widget_set_size_request (label54, 136, 32);

  label55 = gtk_label_new (_("/"));
  gtk_widget_show (label55);
  gtk_fixed_put (GTK_FIXED (fixed4), label55, 672, 240);
  gtk_widget_set_size_request (label55, 56, 24);

  label56 = gtk_label_new (_("/"));
  gtk_widget_show (label56);
  gtk_fixed_put (GTK_FIXED (fixed4), label56, 768, 240);
  gtk_widget_set_size_request (label56, 73, 25);

  label53 = gtk_label_new (_("Quantit\303\251 reserv\303\251e :"));
  gtk_widget_show (label53);
  gtk_fixed_put (GTK_FIXED (fixed4), label53, 400, 184);
  gtk_widget_set_size_request (label53, 168, 32);

  label52 = gtk_label_new (_("nom de l'\303\251quipment :"));
  gtk_widget_show (label52);
  gtk_fixed_put (GTK_FIXED (fixed4), label52, 400, 120);
  gtk_widget_set_size_request (label52, 184, 40);

  combobox__quipmentC = gtk_combo_box_entry_new_text ();
  gtk_widget_show (combobox__quipmentC);
  gtk_fixed_put (GTK_FIXED (fixed4), combobox__quipmentC, 600, 128);
  gtk_widget_set_size_request (combobox__quipmentC, 189, 29);

  reserver___quipment_c = gtk_label_new (_("reserver des \303\251quipement"));
  gtk_widget_show (reserver___quipment_c);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), reserver___quipment_c);

  fixed14 = gtk_fixed_new ();
  gtk_widget_show (fixed14);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed14);

  image58 = create_pixmap (c_b_gestion_coach_coach, "553285991_4122503948018201_4707852305121133389_n.png");
  gtk_widget_show (image58);
  gtk_fixed_put (GTK_FIXED (fixed14), image58, 0, 0);
  gtk_widget_set_size_request (image58, 128, 408);

  fixed15 = gtk_fixed_new ();
  gtk_widget_show (fixed15);
  gtk_fixed_put (GTK_FIXED (fixed14), fixed15, 0, 0);
  gtk_widget_set_size_request (fixed15, 0, 0);

  image60 = create_pixmap (c_b_gestion_coach_coach, "553285991_4122503948018201_4707852305121133389_n.png");
  gtk_widget_show (image60);
  gtk_fixed_put (GTK_FIXED (fixed15), image60, 0, 0);
  gtk_widget_set_size_request (image60, 128, 408);

  image61 = create_pixmap (c_b_gestion_coach_coach, "553285991_4122503948018201_4707852305121133389_n.png");
  gtk_widget_show (image61);
  gtk_fixed_put (GTK_FIXED (fixed14), image61, 0, 400);
  gtk_widget_set_size_request (image61, 128, 224);

  image64 = create_pixmap (c_b_gestion_coach_coach, "551044963_789941773825632_1486066102389035571_n.png");
  gtk_widget_show (image64);
  gtk_fixed_put (GTK_FIXED (fixed14), image64, 1128, 0);
  gtk_widget_set_size_request (image64, 160, 408);

  image66 = create_pixmap (c_b_gestion_coach_coach, "551044963_789941773825632_1486066102389035571_n.png");
  gtk_widget_show (image66);
  gtk_fixed_put (GTK_FIXED (fixed14), image66, 1128, 400);
  gtk_widget_set_size_request (image66, 160, 216);

  label51 = gtk_label_new (_("<span foreground=\"green\"font_desc=\"Arial 30\">BIENVENUE A SPRIFIT </span>"));
  gtk_widget_show (label51);
  gtk_fixed_put (GTK_FIXED (fixed14), label51, 384, 72);
  gtk_widget_set_size_request (label51, 481, 73);
  gtk_label_set_use_markup (GTK_LABEL (label51), TRUE);

  s_inscrire_cours = gtk_button_new_with_mnemonic (_("liste des cous"));
  gtk_widget_show (s_inscrire_cours);
  gtk_fixed_put (GTK_FIXED (fixed14), s_inscrire_cours, 816, 280);
  gtk_widget_set_size_request (s_inscrire_cours, 184, 72);

  coach_reserver_equipm = gtk_button_new_with_mnemonic (_("reserver des \303\251quipments"));
  gtk_widget_show (coach_reserver_equipm);
  gtk_fixed_put (GTK_FIXED (fixed14), coach_reserver_equipm, 240, 280);
  gtk_widget_set_size_request (coach_reserver_equipm, 176, 72);

  acceuil1 = gtk_label_new (_("acceuil1"));
  gtk_widget_show (acceuil1);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 3), acceuil1);

  
    g_signal_connect ((gpointer) button2_valider, "clicked",
                    G_CALLBACK (on_button2_valider_clicked),
                    NULL);
  
  g_signal_connect ((gpointer) button1_mdo, "clicked",
                    G_CALLBACK (on_button1_mdo_clicked),
                    NULL);
  g_signal_connect ((gpointer) button4_sinsc, "clicked",
                    G_CALLBACK (on_button4_sinsc_clicked),
                    NULL);
 
                   
  g_signal_connect ((gpointer) buttonreserver_coach_equipm, "clicked",
                    G_CALLBACK (on_buttonreserver_coach_equipm_clicked),
                    NULL);
  g_signal_connect ((gpointer) s_inscrire_cours, "clicked",
                    G_CALLBACK (on_s_inscrire_cours_clicked),
                    NULL);
  g_signal_connect ((gpointer) coach_reserver_equipm, "clicked",
                    G_CALLBACK (on_coach_reserver_equipm_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (c_b_gestion_coach_coach, c_b_gestion_coach_coach, "c_b_gestion_coach_coach");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_coach, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_coach, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_coach, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_coach, entry1_id, "entry1_id");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_coach, entry2_md, "entry2_md");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_coach, image3, "image3");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_coach, image4, "image4");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_coach, image5, "image5");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_coach, image6, "image6");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_coach, label6_id, "label6_id");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_coach, label7_md, "label7_md");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_coach, image10, "image10");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_coach, image7, "image7");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_coach, image9, "image9");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_coach, image15, "image15");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_coach, button2_valider, "button2_valider");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_coach, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_coach, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_coach, image1, "image1");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_coach, label8, "label8");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_coach, button1_mdo, "button1_mdo");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_coach, image8, "image8");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_coach, label_acc, "label_acc");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_coach, label_acceuil, "label_acceuil");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_coach, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_coach, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_coach, label10, "label10");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_coach, button4_sinsc, "button4_sinsc");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_coach, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_coach, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_coach, image2, "image2");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_coach, label11, "label11");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_coach, image13, "image13");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_coach, image14, "image14");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_coach, image62, "image62");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_coach, image12, "image12");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_coach, labelcal, "labelcal");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_coach, label2_lis_c, "label2_lis_c");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_coach, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_coach, image57, "image57");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_coach, image59, "image59");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_coach, image63, "image63");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_coach, image65, "image65");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_coach, entryquantit___equipm_reserver, "entryquantit___equipm_reserver");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_coach, spinbutton_jour, "spinbutton_jour");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_coach, spinbuttonmois, "spinbuttonmois");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_coach, spinbutton_anne, "spinbutton_anne");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_coach, spinbutton6, "spinbutton6");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_coach, spinbutton7, "spinbutton7");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_coach, buttonreserver_coach_equipm, "buttonreserver_coach_equipm");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_coach, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_coach, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_coach, image67, "image67");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_coach, label60, "label60");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_coach, label57, "label57");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_coach, label58, "label58");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_coach, label59, "label59");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_coach, label54, "label54");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_coach, label55, "label55");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_coach, label56, "label56");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_coach, label53, "label53");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_coach, label52, "label52");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_coach, combobox__quipmentC, "combobox__quipmentC");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_coach, reserver___quipment_c, "reserver___quipment_c");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_coach, fixed14, "fixed14");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_coach, image58, "image58");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_coach, fixed15, "fixed15");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_coach, image60, "image60");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_coach, image61, "image61");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_coach, image64, "image64");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_coach, image66, "image66");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_coach, label51, "label51");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_coach, s_inscrire_cours, "s_inscrire_cours");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_coach, coach_reserver_equipm, "coach_reserver_equipm");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_coach, acceuil1, "acceuil1");

  return c_b_gestion_coach_coach;
}

GtkWidget*
create_c_b_gestion_coach_add (void)
{
  GtkWidget *c_b_gestion_coach_add;
  GtkWidget *fixed5;
  GtkWidget *notebook2;
  GtkWidget *fixed6;
  GtkWidget *entry1_id;
  GtkWidget *label20_md;
  GtkWidget *entry2_md;
  GtkWidget *image19;
  GtkWidget *image20;
  GtkWidget *image17;
  GtkWidget *image18;
  GtkWidget *label18;
  GtkWidget *label19_id;
  GtkWidget *button1_mdo;
  GtkWidget *button2_valider;
  GtkWidget *alignment3_vald;
  GtkWidget *hbox3;
  GtkWidget *image16;
  GtkWidget *label21_vald;
  GtkWidget *label12_add;
  GtkWidget *fixed7;
  GtkWidget *image30;
  GtkWidget *image35;
  GtkWidget *image40;
  GtkWidget *image25;
  GtkWidget *label22;
  GtkWidget *button4_supprimer_coach;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image22;
  GtkWidget *label24_sup;
  GtkWidget *button3_ajouter_coach;
  GtkWidget *alignment4_aj;
  GtkWidget *hbox4;
  GtkWidget *image21;
  GtkWidget *label23_aj;
  GtkWidget *button5_modofier_coach;
  GtkWidget *alignment6_mod;
  GtkWidget *hbox6;
  GtkWidget *image23;
  GtkWidget *label25_mod;
  GtkWidget *button6_chercher_coach;
  GtkWidget *alignment7_cher;
  GtkWidget *hbox7;
  GtkWidget *image24;
  GtkWidget *label26_cher;
  GtkWidget *label13_gc;
  GtkWidget *fixed8;
  GtkWidget *image26;
  GtkWidget *image31;
  GtkWidget *image41;
  GtkWidget *label27_nom;
  GtkWidget *entry1_nom;
  GtkWidget *label28_pren;
  GtkWidget *entry2_pren;
  GtkWidget *calendar1_dn;
  GtkWidget *label29_dn;
  GtkWidget *entry3_numtel;
  GtkWidget *label30_numtel;
  GtkWidget *label31_sal;
  GtkWidget *label32_cours;
  GtkObject *spinbutton1_cap_adj;
  GtkWidget *spinbutton1_cap;
  GtkWidget *image36;
  GtkWidget *label33_cap;
  GtkWidget *label34_contr;
  GtkWidget *label35_md;
  GtkWidget *entry4_md;
  GtkWidget *entry5_id;
  GtkWidget *label36_id;
  GtkWidget *radiobutton1_1a;
  GSList *radiobutton1_1a_group = NULL;
  GtkWidget *radiobutton2_2a;
  GtkWidget *radiobutton3_3a;
  GtkWidget *checkbutton3_BP;
  GtkWidget *checkbutton2_BA;
  GtkWidget *checkbutton1_BC;
  GtkWidget *checkbutton4_BB;
  GtkWidget *checkbutton8_LD;
  GtkWidget *checkbutton7_zoum;
  GtkWidget *checkbutton6_yoga;
  GtkWidget *checkbutton5_Car;
  GtkWidget *comboboxentry3;
  GtkWidget *button1_enregistrer_A;
  GtkWidget *alignment8_enrg;
  GtkWidget *hbox8;
  GtkWidget *image45;
  GtkWidget *label37;
  GtkWidget *label14_ajouter;
  GtkWidget *fixed9;
  GtkWidget *image27;
  GtkWidget *image32;
  GtkWidget *image37;
  GtkWidget *image42;
  GtkWidget *entry11_id;
  GtkWidget *label49_id;
  GtkWidget *button3_supp;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image51;
  GtkWidget *label50;
  GtkWidget *label15_supp;
  GtkWidget *fixed10;
  GtkWidget *image28;
  GtkWidget *image33;
  GtkWidget *image38;
  GtkWidget *image43;
  GtkWidget *fixed12;
  GtkWidget *image46;
  GtkWidget *image47;
  GtkWidget *image48;
  GtkWidget *entry6_nom;
  GtkWidget *label39;
  GtkWidget *entry7_prenom;
  GtkWidget *calendar2;
  GtkWidget *label40;
  GtkWidget *entry8_numtel;
  GtkWidget *label41;
  GtkWidget *label42;
  GtkObject *spinbutton2_adj;
  GtkWidget *spinbutton2;
  GtkWidget *image49;
  GtkWidget *label45;
  GtkWidget *label46;
  GtkWidget *entry9_md_M;
  GtkWidget *entry10_id_M;
  GtkWidget *label47;
  GtkWidget *label38;
  GtkWidget *comboboxentry2;
  GtkWidget *radiobutton4_1ans_M;
  GSList *radiobutton4_1ans_M_group = NULL;
  GtkWidget *radiobutton5_2ans_M;
  GtkWidget *radiobutton6_3ans_M;
  GtkWidget *checkbutton13_C_M;
  GtkWidget *checkbutton16_LD_M;
  GtkWidget *checkbutton15_Z_M;
  GtkWidget *checkbutton14_Y_M;
  GtkWidget *checkbutton9_BC_M;
  GtkWidget *checkbutton10_BA_M;
  GtkWidget *checkbutton11_BP_M;
  GtkWidget *checkbutton12_BB_M;
  GtkWidget *label43;
  GtkWidget *label44;
  GtkWidget *label61;
  GtkWidget *entryid_modifer;
  GtkWidget *button_chercher_id_M;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image68;
  GtkWidget *label62;
  GtkWidget *button2_enregistrer_M;
  GtkWidget *alignment9_enrg;
  GtkWidget *hbox9;
  GtkWidget *image50;
  GtkWidget *label48_mod;
  GtkWidget *label16_modf;
  GtkWidget *fixed11;
  GtkWidget *image29;
  GtkWidget *image34;
  GtkWidget *image39;
  GtkWidget *image44;
  GtkWidget *fixed13;
  GtkWidget *image52;
  GtkWidget *image53;
  GtkWidget *image54;
  GtkWidget *image55;
  GtkWidget *entry12_id;
  GtkWidget *label52_id;
  GtkWidget *button4_chercher;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image56;
  GtkWidget *label51_cher;
  GtkWidget *label17_cher;

  c_b_gestion_coach_add = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (c_b_gestion_coach_add), _("c_b_gestion coach.add"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (c_b_gestion_coach_add), fixed5);

  notebook2 = gtk_notebook_new ();
  gtk_widget_show (notebook2);
  gtk_fixed_put (GTK_FIXED (fixed5), notebook2, 0, 0);
  gtk_widget_set_size_request (notebook2, 1288, 640);

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (notebook2), fixed6);

  entry1_id = gtk_entry_new ();
  gtk_widget_show (entry1_id);
  gtk_fixed_put (GTK_FIXED (fixed6), entry1_id, 496, 216);
  gtk_widget_set_size_request (entry1_id, 248, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1_id), 8226);

  label20_md = gtk_label_new (_(" ENTRER VOTRE MOT DE PASSE  "));
  gtk_widget_show (label20_md);
  gtk_fixed_put (GTK_FIXED (fixed6), label20_md, 496, 264);
  gtk_widget_set_size_request (label20_md, 248, 40);

  entry2_md = gtk_entry_new ();
  gtk_widget_show (entry2_md);
  gtk_fixed_put (GTK_FIXED (fixed6), entry2_md, 496, 312);
  gtk_widget_set_size_request (entry2_md, 248, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2_md), 8226);

  image19 = create_pixmap (c_b_gestion_coach_add, "553285991_4122503948018201_4707852305121133389_n.png");
  gtk_widget_show (image19);
  gtk_fixed_put (GTK_FIXED (fixed6), image19, 0, 0);
  gtk_widget_set_size_request (image19, 128, 408);

  image20 = create_pixmap (c_b_gestion_coach_add, "553285991_4122503948018201_4707852305121133389_n.png");
  gtk_widget_show (image20);
  gtk_fixed_put (GTK_FIXED (fixed6), image20, 0, 400);
  gtk_widget_set_size_request (image20, 128, 224);

  image17 = create_pixmap (c_b_gestion_coach_add, "551044963_789941773825632_1486066102389035571_n.png");
  gtk_widget_show (image17);
  gtk_fixed_put (GTK_FIXED (fixed6), image17, 1128, 0);
  gtk_widget_set_size_request (image17, 160, 408);

  image18 = create_pixmap (c_b_gestion_coach_add, "551044963_789941773825632_1486066102389035571_n.png");
  gtk_widget_show (image18);
  gtk_fixed_put (GTK_FIXED (fixed6), image18, 1128, 400);
  gtk_widget_set_size_request (image18, 160, 216);

  label18 = gtk_label_new_with_mnemonic (_("<span foreground=\"green\"font_desc=\"Arial 30\">BIENVENUE A SPRIFIT !\nVEULLEZ ENTRER VOS DONNEES </span>"));
  gtk_widget_show (label18);
  gtk_fixed_put (GTK_FIXED (fixed6), label18, 256, 32);
  gtk_widget_set_size_request (label18, 720, 152);
  gtk_label_set_use_markup (GTK_LABEL (label18), TRUE);
  gtk_label_set_justify (GTK_LABEL (label18), GTK_JUSTIFY_CENTER);

  label19_id = gtk_label_new (_(" ENTRER VOTRE ID "));
  gtk_widget_show (label19_id);
  gtk_fixed_put (GTK_FIXED (fixed6), label19_id, 512, 176);
  gtk_widget_set_size_request (label19_id, 208, 48);

  button1_mdo = gtk_button_new_with_mnemonic (_("MOT DE PASSE OUBLIE ?"));
  gtk_widget_show (button1_mdo);
  gtk_fixed_put (GTK_FIXED (fixed6), button1_mdo, 512, 360);
  gtk_widget_set_size_request (button1_mdo, 216, 32);

  button2_valider = gtk_button_new ();
  gtk_widget_show (button2_valider);
  gtk_fixed_put (GTK_FIXED (fixed6), button2_valider, 528, 448);
  gtk_widget_set_size_request (button2_valider, 176, 64);

  alignment3_vald = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3_vald);
  gtk_container_add (GTK_CONTAINER (button2_valider), alignment3_vald);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3_vald), hbox3);

  image16 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox3), image16, FALSE, FALSE, 0);

  label21_vald = gtk_label_new_with_mnemonic (_("Valider"));
  gtk_widget_show (label21_vald);
  gtk_box_pack_start (GTK_BOX (hbox3), label21_vald, FALSE, FALSE, 0);

  label12_add = gtk_label_new (_("Addministrateur"));
  gtk_widget_show (label12_add);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 0), label12_add);

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (notebook2), fixed7);

  image30 = create_pixmap (c_b_gestion_coach_add, "553285991_4122503948018201_4707852305121133389_n.png");
  gtk_widget_show (image30);
  gtk_fixed_put (GTK_FIXED (fixed7), image30, 0, 400);
  gtk_widget_set_size_request (image30, 128, 224);

  image35 = create_pixmap (c_b_gestion_coach_add, "551044963_789941773825632_1486066102389035571_n.png");
  gtk_widget_show (image35);
  gtk_fixed_put (GTK_FIXED (fixed7), image35, 1128, 0);
  gtk_widget_set_size_request (image35, 160, 408);

  image40 = create_pixmap (c_b_gestion_coach_add, "551044963_789941773825632_1486066102389035571_n.png");
  gtk_widget_show (image40);
  gtk_fixed_put (GTK_FIXED (fixed7), image40, 1128, 400);
  gtk_widget_set_size_request (image40, 160, 216);

  image25 = create_pixmap (c_b_gestion_coach_add, "553285991_4122503948018201_4707852305121133389_n.png");
  gtk_widget_show (image25);
  gtk_fixed_put (GTK_FIXED (fixed7), image25, 0, 0);
  gtk_widget_set_size_request (image25, 128, 408);

  label22 = gtk_label_new (_("<span foreground=\"green\"font_desc=\"Arial 30\">GESTION DES COACHS </span>"));
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (fixed7), label22, 296, 64);
  gtk_widget_set_size_request (label22, 616, 72);
  gtk_label_set_use_markup (GTK_LABEL (label22), TRUE);

  button4_supprimer_coach = gtk_button_new ();
  gtk_widget_show (button4_supprimer_coach);
  gtk_fixed_put (GTK_FIXED (fixed7), button4_supprimer_coach, 392, 296);
  gtk_widget_set_size_request (button4_supprimer_coach, 184, 64);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (button4_supprimer_coach), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image22 = gtk_image_new_from_stock ("gtk-remove", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image22);
  gtk_box_pack_start (GTK_BOX (hbox5), image22, FALSE, FALSE, 0);

  label24_sup = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label24_sup);
  gtk_box_pack_start (GTK_BOX (hbox5), label24_sup, FALSE, FALSE, 0);

  button3_ajouter_coach = gtk_button_new ();
  gtk_widget_show (button3_ajouter_coach);
  gtk_fixed_put (GTK_FIXED (fixed7), button3_ajouter_coach, 88, 296);
  gtk_widget_set_size_request (button3_ajouter_coach, 184, 64);

  alignment4_aj = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4_aj);
  gtk_container_add (GTK_CONTAINER (button3_ajouter_coach), alignment4_aj);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4_aj), hbox4);

  image21 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image21);
  gtk_box_pack_start (GTK_BOX (hbox4), image21, FALSE, FALSE, 0);

  label23_aj = gtk_label_new_with_mnemonic (_("Ajouer"));
  gtk_widget_show (label23_aj);
  gtk_box_pack_start (GTK_BOX (hbox4), label23_aj, FALSE, FALSE, 0);

  button5_modofier_coach = gtk_button_new ();
  gtk_widget_show (button5_modofier_coach);
  gtk_fixed_put (GTK_FIXED (fixed7), button5_modofier_coach, 704, 296);
  gtk_widget_set_size_request (button5_modofier_coach, 184, 64);

  alignment6_mod = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6_mod);
  gtk_container_add (GTK_CONTAINER (button5_modofier_coach), alignment6_mod);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6_mod), hbox6);

  image23 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image23);
  gtk_box_pack_start (GTK_BOX (hbox6), image23, FALSE, FALSE, 0);

  label25_mod = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label25_mod);
  gtk_box_pack_start (GTK_BOX (hbox6), label25_mod, FALSE, FALSE, 0);

  button6_chercher_coach = gtk_button_new ();
  gtk_widget_show (button6_chercher_coach);
  gtk_fixed_put (GTK_FIXED (fixed7), button6_chercher_coach, 1000, 296);
  gtk_widget_set_size_request (button6_chercher_coach, 184, 64);

  alignment7_cher = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7_cher);
  gtk_container_add (GTK_CONTAINER (button6_chercher_coach), alignment7_cher);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7_cher), hbox7);

  image24 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image24);
  gtk_box_pack_start (GTK_BOX (hbox7), image24, FALSE, FALSE, 0);

  label26_cher = gtk_label_new_with_mnemonic (_("Chercher"));
  gtk_widget_show (label26_cher);
  gtk_box_pack_start (GTK_BOX (hbox7), label26_cher, FALSE, FALSE, 0);

  label13_gc = gtk_label_new (_("Gestion des coach"));
  gtk_widget_show (label13_gc);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 1), label13_gc);

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (notebook2), fixed8);

  image26 = create_pixmap (c_b_gestion_coach_add, "553285991_4122503948018201_4707852305121133389_n.png");
  gtk_widget_show (image26);
  gtk_fixed_put (GTK_FIXED (fixed8), image26, 0, 0);
  gtk_widget_set_size_request (image26, 128, 408);

  image31 = create_pixmap (c_b_gestion_coach_add, "553285991_4122503948018201_4707852305121133389_n.png");
  gtk_widget_show (image31);
  gtk_fixed_put (GTK_FIXED (fixed8), image31, 0, 400);
  gtk_widget_set_size_request (image31, 128, 224);

  image41 = create_pixmap (c_b_gestion_coach_add, "551044963_789941773825632_1486066102389035571_n.png");
  gtk_widget_show (image41);
  gtk_fixed_put (GTK_FIXED (fixed8), image41, 1128, 400);
  gtk_widget_set_size_request (image41, 160, 216);

  label27_nom = gtk_label_new (_("Nom :"));
  gtk_widget_show (label27_nom);
  gtk_fixed_put (GTK_FIXED (fixed8), label27_nom, 120, 56);
  gtk_widget_set_size_request (label27_nom, 72, 24);

  entry1_nom = gtk_entry_new ();
  gtk_widget_show (entry1_nom);
  gtk_fixed_put (GTK_FIXED (fixed8), entry1_nom, 240, 56);
  gtk_widget_set_size_request (entry1_nom, 192, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1_nom), 8226);

  label28_pren = gtk_label_new (_("Pr\303\251nom :"));
  gtk_widget_show (label28_pren);
  gtk_fixed_put (GTK_FIXED (fixed8), label28_pren, 104, 112);
  gtk_widget_set_size_request (label28_pren, 104, 32);
  GTK_WIDGET_SET_FLAGS (label28_pren, GTK_CAN_FOCUS);
  gtk_label_set_selectable (GTK_LABEL (label28_pren), TRUE);

  entry2_pren = gtk_entry_new ();
  gtk_widget_show (entry2_pren);
  gtk_fixed_put (GTK_FIXED (fixed8), entry2_pren, 240, 112);
  gtk_widget_set_size_request (entry2_pren, 192, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2_pren), 8226);

  calendar1_dn = gtk_calendar_new ();
  gtk_widget_show (calendar1_dn);
  gtk_fixed_put (GTK_FIXED (fixed8), calendar1_dn, 240, 168);
  gtk_widget_set_size_request (calendar1_dn, 240, 168);
  gtk_calendar_display_options (GTK_CALENDAR (calendar1_dn),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  label29_dn = gtk_label_new (_("Date de naissence :"));
  gtk_widget_show (label29_dn);
  gtk_fixed_put (GTK_FIXED (fixed8), label29_dn, 80, 168);
  gtk_widget_set_size_request (label29_dn, 152, 40);

  entry3_numtel = gtk_entry_new ();
  gtk_widget_show (entry3_numtel);
  gtk_fixed_put (GTK_FIXED (fixed8), entry3_numtel, 240, 368);
  gtk_widget_set_size_request (entry3_numtel, 192, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3_numtel), 8226);

  label30_numtel = gtk_label_new (_("Num de T\303\251l :"));
  gtk_widget_show (label30_numtel);
  gtk_fixed_put (GTK_FIXED (fixed8), label30_numtel, 104, 368);
  gtk_widget_set_size_request (label30_numtel, 128, 32);

  label31_sal = gtk_label_new (_("Salle de sport :"));
  gtk_widget_show (label31_sal);
  gtk_fixed_put (GTK_FIXED (fixed8), label31_sal, 104, 432);
  gtk_widget_set_size_request (label31_sal, 128, 32);

  label32_cours = gtk_label_new (_("Les cours :"));
  gtk_widget_show (label32_cours);
  gtk_fixed_put (GTK_FIXED (fixed8), label32_cours, 744, 48);
  gtk_widget_set_size_request (label32_cours, 104, 32);

  spinbutton1_cap_adj = gtk_adjustment_new (1, 0, 5, 1, 10, 10);
  spinbutton1_cap = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1_cap_adj), 1, 0);
  gtk_widget_show (spinbutton1_cap);
  gtk_fixed_put (GTK_FIXED (fixed8), spinbutton1_cap, 1016, 240);
  gtk_widget_set_size_request (spinbutton1_cap, 144, 24);

  image36 = create_pixmap (c_b_gestion_coach_add, "551044963_789941773825632_1486066102389035571_n.png");
  gtk_widget_show (image36);
  gtk_fixed_put (GTK_FIXED (fixed8), image36, 1128, 0);
  gtk_widget_set_size_request (image36, 160, 408);

  label33_cap = gtk_label_new (_("capacit\303\251 maximale journaliere :"));
  gtk_widget_show (label33_cap);
  gtk_fixed_put (GTK_FIXED (fixed8), label33_cap, 752, 240);
  gtk_widget_set_size_request (label33_cap, 224, 32);

  label34_contr = gtk_label_new (_("Contrat :"));
  gtk_widget_show (label34_contr);
  gtk_fixed_put (GTK_FIXED (fixed8), label34_contr, 840, 312);
  gtk_widget_set_size_request (label34_contr, 128, 24);

  label35_md = gtk_label_new (_("Mot de passe :"));
  gtk_widget_show (label35_md);
  gtk_fixed_put (GTK_FIXED (fixed8), label35_md, 800, 432);
  gtk_widget_set_size_request (label35_md, 168, 32);

  entry4_md = gtk_entry_new ();
  gtk_widget_show (entry4_md);
  gtk_fixed_put (GTK_FIXED (fixed8), entry4_md, 984, 432);
  gtk_widget_set_size_request (entry4_md, 192, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4_md), 8226);

  entry5_id = gtk_entry_new ();
  gtk_widget_show (entry5_id);
  gtk_fixed_put (GTK_FIXED (fixed8), entry5_id, 984, 480);
  gtk_widget_set_size_request (entry5_id, 192, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5_id), 8226);

  label36_id = gtk_label_new (_("ID :"));
  gtk_widget_show (label36_id);
  gtk_fixed_put (GTK_FIXED (fixed8), label36_id, 856, 480);
  gtk_widget_set_size_request (label36_id, 80, 32);

  radiobutton1_1a = gtk_radio_button_new_with_mnemonic (NULL, _("1 ans"));
  gtk_widget_show (radiobutton1_1a);
  gtk_fixed_put (GTK_FIXED (fixed8), radiobutton1_1a, 1024, 312);
  gtk_widget_set_size_request (radiobutton1_1a, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1_1a), radiobutton1_1a_group);
  radiobutton1_1a_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1_1a));

  radiobutton2_2a = gtk_radio_button_new_with_mnemonic (NULL, _("2 ans"));
  gtk_widget_show (radiobutton2_2a);
  gtk_fixed_put (GTK_FIXED (fixed8), radiobutton2_2a, 1024, 352);
  gtk_widget_set_size_request (radiobutton2_2a, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton2_2a), radiobutton1_1a_group);
  radiobutton1_1a_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton2_2a));

  radiobutton3_3a = gtk_radio_button_new_with_mnemonic (NULL, _("3 ans"));
  gtk_widget_show (radiobutton3_3a);
  gtk_fixed_put (GTK_FIXED (fixed8), radiobutton3_3a, 1024, 392);
  gtk_widget_set_size_request (radiobutton3_3a, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton3_3a), radiobutton1_1a_group);
  radiobutton1_1a_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton3_3a));

  checkbutton3_BP = gtk_check_button_new_with_mnemonic (_("Body Pump"));
  gtk_widget_show (checkbutton3_BP);
  gtk_fixed_put (GTK_FIXED (fixed8), checkbutton3_BP, 848, 136);
  gtk_widget_set_size_request (checkbutton3_BP, 118, 24);

  checkbutton2_BA = gtk_check_button_new_with_mnemonic (_("Body Attack"));
  gtk_widget_show (checkbutton2_BA);
  gtk_fixed_put (GTK_FIXED (fixed8), checkbutton2_BA, 848, 96);
  gtk_widget_set_size_request (checkbutton2_BA, 118, 24);

  checkbutton1_BC = gtk_check_button_new_with_mnemonic ("Body combat");
  gtk_button_set_use_stock (GTK_BUTTON (checkbutton1_BC), TRUE);
  gtk_widget_show (checkbutton1_BC);
  gtk_fixed_put (GTK_FIXED (fixed8), checkbutton1_BC, 848, 56);
  gtk_widget_set_size_request (checkbutton1_BC, 118, 24);

  checkbutton4_BB = gtk_check_button_new_with_mnemonic (_("Body Balance"));
  gtk_widget_show (checkbutton4_BB);
  gtk_fixed_put (GTK_FIXED (fixed8), checkbutton4_BB, 848, 176);
  gtk_widget_set_size_request (checkbutton4_BB, 118, 24);

  checkbutton8_LD = gtk_check_button_new_with_mnemonic (_("Lesmiless Dance"));
  gtk_widget_show (checkbutton8_LD);
  gtk_fixed_put (GTK_FIXED (fixed8), checkbutton8_LD, 1048, 176);
  gtk_widget_set_size_request (checkbutton8_LD, 144, 24);

  checkbutton7_zoum = gtk_check_button_new_with_mnemonic (_("Zoumba"));
  gtk_widget_show (checkbutton7_zoum);
  gtk_fixed_put (GTK_FIXED (fixed8), checkbutton7_zoum, 1048, 136);
  gtk_widget_set_size_request (checkbutton7_zoum, 118, 24);

  checkbutton6_yoga = gtk_check_button_new_with_mnemonic (_("Yoga"));
  gtk_widget_show (checkbutton6_yoga);
  gtk_fixed_put (GTK_FIXED (fixed8), checkbutton6_yoga, 1048, 96);
  gtk_widget_set_size_request (checkbutton6_yoga, 118, 24);

  checkbutton5_Car = gtk_check_button_new_with_mnemonic (_("Cardio"));
  gtk_widget_show (checkbutton5_Car);
  gtk_fixed_put (GTK_FIXED (fixed8), checkbutton5_Car, 1048, 56);
  gtk_widget_set_size_request (checkbutton5_Car, 118, 24);

  comboboxentry3 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry3);
  gtk_fixed_put (GTK_FIXED (fixed8), comboboxentry3, 240, 432);
  gtk_widget_set_size_request (comboboxentry3, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("californiaGym marsa"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("californiaGym sokra"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("californiaGym centre urbain nord"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("californiaGym ariana"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry3), _("californiaGym lac"));

  button1_enregistrer_A = gtk_button_new ();
  gtk_widget_show (button1_enregistrer_A);
  gtk_fixed_put (GTK_FIXED (fixed8), button1_enregistrer_A, 544, 496);
  gtk_widget_set_size_request (button1_enregistrer_A, 184, 64);

  alignment8_enrg = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8_enrg);
  gtk_container_add (GTK_CONTAINER (button1_enregistrer_A), alignment8_enrg);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8_enrg), hbox8);

  image45 = gtk_image_new_from_stock ("gtk-save", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image45);
  gtk_box_pack_start (GTK_BOX (hbox8), image45, FALSE, FALSE, 0);

  label37 = gtk_label_new_with_mnemonic (_("Enregistrer"));
  gtk_widget_show (label37);
  gtk_box_pack_start (GTK_BOX (hbox8), label37, FALSE, FALSE, 0);

  label14_ajouter = gtk_label_new (_("Ajouter"));
  gtk_widget_show (label14_ajouter);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 2), label14_ajouter);

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_container_add (GTK_CONTAINER (notebook2), fixed9);

  image27 = create_pixmap (c_b_gestion_coach_add, "553285991_4122503948018201_4707852305121133389_n.png");
  gtk_widget_show (image27);
  gtk_fixed_put (GTK_FIXED (fixed9), image27, 0, 0);
  gtk_widget_set_size_request (image27, 128, 408);

  image32 = create_pixmap (c_b_gestion_coach_add, "553285991_4122503948018201_4707852305121133389_n.png");
  gtk_widget_show (image32);
  gtk_fixed_put (GTK_FIXED (fixed9), image32, 0, 400);
  gtk_widget_set_size_request (image32, 128, 224);

  image37 = create_pixmap (c_b_gestion_coach_add, "551044963_789941773825632_1486066102389035571_n.png");
  gtk_widget_show (image37);
  gtk_fixed_put (GTK_FIXED (fixed9), image37, 1128, 0);
  gtk_widget_set_size_request (image37, 160, 408);

  image42 = create_pixmap (c_b_gestion_coach_add, "551044963_789941773825632_1486066102389035571_n.png");
  gtk_widget_show (image42);
  gtk_fixed_put (GTK_FIXED (fixed9), image42, 1128, 400);
  gtk_widget_set_size_request (image42, 160, 216);

  entry11_id = gtk_entry_new ();
  gtk_widget_show (entry11_id);
  gtk_fixed_put (GTK_FIXED (fixed9), entry11_id, 656, 168);
  gtk_widget_set_size_request (entry11_id, 208, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry11_id), 8226);

  label49_id = gtk_label_new (_("<span foreground=\"black\"font_desc=\"Arial 20\">DONNER L'ID </span>"));
  gtk_widget_show (label49_id);
  gtk_fixed_put (GTK_FIXED (fixed9), label49_id, 352, 160);
  gtk_widget_set_size_request (label49_id, 320, 48);
  gtk_label_set_use_markup (GTK_LABEL (label49_id), TRUE);

  button3_supp = gtk_button_new ();
  gtk_widget_show (button3_supp);
  gtk_fixed_put (GTK_FIXED (fixed9), button3_supp, 544, 336);
  gtk_widget_set_size_request (button3_supp, 184, 72);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (button3_supp), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image51 = gtk_image_new_from_stock ("gtk-remove", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image51);
  gtk_box_pack_start (GTK_BOX (hbox10), image51, FALSE, FALSE, 0);

  label50 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label50);
  gtk_box_pack_start (GTK_BOX (hbox10), label50, FALSE, FALSE, 0);

  label15_supp = gtk_label_new (_("Supprimer"));
  gtk_widget_show (label15_supp);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 3), label15_supp);

  fixed10 = gtk_fixed_new ();
  gtk_widget_show (fixed10);
  gtk_container_add (GTK_CONTAINER (notebook2), fixed10);

  image28 = create_pixmap (c_b_gestion_coach_add, "553285991_4122503948018201_4707852305121133389_n.png");
  gtk_widget_show (image28);
  gtk_fixed_put (GTK_FIXED (fixed10), image28, 0, 0);
  gtk_widget_set_size_request (image28, 128, 408);

  image33 = create_pixmap (c_b_gestion_coach_add, "553285991_4122503948018201_4707852305121133389_n.png");
  gtk_widget_show (image33);
  gtk_fixed_put (GTK_FIXED (fixed10), image33, 0, 400);
  gtk_widget_set_size_request (image33, 128, 224);

  image38 = create_pixmap (c_b_gestion_coach_add, "551044963_789941773825632_1486066102389035571_n.png");
  gtk_widget_show (image38);
  gtk_fixed_put (GTK_FIXED (fixed10), image38, 1128, 0);
  gtk_widget_set_size_request (image38, 160, 408);

  image43 = create_pixmap (c_b_gestion_coach_add, "551044963_789941773825632_1486066102389035571_n.png");
  gtk_widget_show (image43);
  gtk_fixed_put (GTK_FIXED (fixed10), image43, 1128, 400);
  gtk_widget_set_size_request (image43, 160, 216);

  fixed12 = gtk_fixed_new ();
  gtk_widget_show (fixed12);
  gtk_fixed_put (GTK_FIXED (fixed10), fixed12, 0, 0);
  gtk_widget_set_size_request (fixed12, 0, 0);

  image46 = create_pixmap (c_b_gestion_coach_add, "553285991_4122503948018201_4707852305121133389_n.png");
  gtk_widget_show (image46);
  gtk_fixed_put (GTK_FIXED (fixed12), image46, 0, 0);
  gtk_widget_set_size_request (image46, 128, 408);

  image47 = create_pixmap (c_b_gestion_coach_add, "553285991_4122503948018201_4707852305121133389_n.png");
  gtk_widget_show (image47);
  gtk_fixed_put (GTK_FIXED (fixed12), image47, 0, 400);
  gtk_widget_set_size_request (image47, 128, 224);

  image48 = create_pixmap (c_b_gestion_coach_add, "551044963_789941773825632_1486066102389035571_n.png");
  gtk_widget_show (image48);
  gtk_fixed_put (GTK_FIXED (fixed12), image48, 1128, 400);
  gtk_widget_set_size_request (image48, 160, 216);

  entry6_nom = gtk_entry_new ();
  gtk_widget_show (entry6_nom);
  gtk_fixed_put (GTK_FIXED (fixed12), entry6_nom, 240, 56);
  gtk_widget_set_size_request (entry6_nom, 192, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry6_nom), 8226);

  label39 = gtk_label_new (_("Pr\303\251nom :"));
  gtk_widget_show (label39);
  gtk_fixed_put (GTK_FIXED (fixed12), label39, 104, 112);
  gtk_widget_set_size_request (label39, 104, 32);
  GTK_WIDGET_SET_FLAGS (label39, GTK_CAN_FOCUS);
  gtk_label_set_selectable (GTK_LABEL (label39), TRUE);

  entry7_prenom = gtk_entry_new ();
  gtk_widget_show (entry7_prenom);
  gtk_fixed_put (GTK_FIXED (fixed12), entry7_prenom, 240, 112);
  gtk_widget_set_size_request (entry7_prenom, 192, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry7_prenom), 8226);

  calendar2 = gtk_calendar_new ();
  gtk_widget_show (calendar2);
  gtk_fixed_put (GTK_FIXED (fixed12), calendar2, 240, 168);
  gtk_widget_set_size_request (calendar2, 240, 168);
  gtk_calendar_display_options (GTK_CALENDAR (calendar2),
                                GTK_CALENDAR_SHOW_HEADING
                                | GTK_CALENDAR_SHOW_DAY_NAMES);

  label40 = gtk_label_new (_("Date de naissence :"));
  gtk_widget_show (label40);
  gtk_fixed_put (GTK_FIXED (fixed12), label40, 80, 168);
  gtk_widget_set_size_request (label40, 152, 40);

  entry8_numtel = gtk_entry_new ();
  gtk_widget_show (entry8_numtel);
  gtk_fixed_put (GTK_FIXED (fixed12), entry8_numtel, 240, 368);
  gtk_widget_set_size_request (entry8_numtel, 192, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry8_numtel), 8226);

  label41 = gtk_label_new (_("Num de T\303\251l :"));
  gtk_widget_show (label41);
  gtk_fixed_put (GTK_FIXED (fixed12), label41, 104, 368);
  gtk_widget_set_size_request (label41, 128, 32);

  label42 = gtk_label_new (_("Salle de sport :"));
  gtk_widget_show (label42);
  gtk_fixed_put (GTK_FIXED (fixed12), label42, 104, 432);
  gtk_widget_set_size_request (label42, 128, 32);

  spinbutton2_adj = gtk_adjustment_new (1, 0, 5, 1, 10, 10);
  spinbutton2 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton2_adj), 1, 0);
  gtk_widget_show (spinbutton2);
  gtk_fixed_put (GTK_FIXED (fixed12), spinbutton2, 1016, 240);
  gtk_widget_set_size_request (spinbutton2, 144, 24);

  image49 = create_pixmap (c_b_gestion_coach_add, "551044963_789941773825632_1486066102389035571_n.png");
  gtk_widget_show (image49);
  gtk_fixed_put (GTK_FIXED (fixed12), image49, 1128, 0);
  gtk_widget_set_size_request (image49, 160, 408);

  label45 = gtk_label_new (_("Contrat :"));
  gtk_widget_show (label45);
  gtk_fixed_put (GTK_FIXED (fixed12), label45, 840, 312);
  gtk_widget_set_size_request (label45, 128, 24);

  label46 = gtk_label_new (_("Mot de passe :"));
  gtk_widget_show (label46);
  gtk_fixed_put (GTK_FIXED (fixed12), label46, 800, 432);
  gtk_widget_set_size_request (label46, 168, 32);

  entry9_md_M = gtk_entry_new ();
  gtk_widget_show (entry9_md_M);
  gtk_fixed_put (GTK_FIXED (fixed12), entry9_md_M, 984, 432);
  gtk_widget_set_size_request (entry9_md_M, 192, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry9_md_M), 8226);

  entry10_id_M = gtk_entry_new ();
  gtk_widget_show (entry10_id_M);
  gtk_fixed_put (GTK_FIXED (fixed12), entry10_id_M, 984, 480);
  gtk_widget_set_size_request (entry10_id_M, 192, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry10_id_M), 8226);

  label47 = gtk_label_new (_("ID :"));
  gtk_widget_show (label47);
  gtk_fixed_put (GTK_FIXED (fixed12), label47, 856, 480);
  gtk_widget_set_size_request (label47, 80, 32);

  label38 = gtk_label_new (_("Nom :"));
  gtk_widget_show (label38);
  gtk_fixed_put (GTK_FIXED (fixed12), label38, 120, 56);
  gtk_widget_set_size_request (label38, 72, 24);

  comboboxentry2 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentry2);
  gtk_fixed_put (GTK_FIXED (fixed12), comboboxentry2, 240, 432);
  gtk_widget_set_size_request (comboboxentry2, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("californiaGym marsa"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("californiaGym sokra"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("californiaGym centre urbain nord"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("californiaGym ariana"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentry2), _("californiaGym lac"));

  radiobutton4_1ans_M = gtk_radio_button_new_with_mnemonic (NULL, _("1 ans"));
  gtk_widget_show (radiobutton4_1ans_M);
  gtk_fixed_put (GTK_FIXED (fixed12), radiobutton4_1ans_M, 1024, 312);
  gtk_widget_set_size_request (radiobutton4_1ans_M, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton4_1ans_M), radiobutton4_1ans_M_group);
  radiobutton4_1ans_M_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton4_1ans_M));

  radiobutton5_2ans_M = gtk_radio_button_new_with_mnemonic (NULL, _("2 ans"));
  gtk_widget_show (radiobutton5_2ans_M);
  gtk_fixed_put (GTK_FIXED (fixed12), radiobutton5_2ans_M, 1024, 352);
  gtk_widget_set_size_request (radiobutton5_2ans_M, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton5_2ans_M), radiobutton1_1a_group);
  radiobutton1_1a_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton5_2ans_M));

  radiobutton6_3ans_M = gtk_radio_button_new_with_mnemonic (NULL, _("3 ans"));
  gtk_widget_show (radiobutton6_3ans_M);
  gtk_fixed_put (GTK_FIXED (fixed12), radiobutton6_3ans_M, 1024, 392);
  gtk_widget_set_size_request (radiobutton6_3ans_M, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton6_3ans_M), radiobutton1_1a_group);
  radiobutton1_1a_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton6_3ans_M));

  checkbutton13_C_M = gtk_check_button_new_with_mnemonic (_("Cardio"));
  gtk_widget_show (checkbutton13_C_M);
  gtk_fixed_put (GTK_FIXED (fixed12), checkbutton13_C_M, 1080, 48);
  gtk_widget_set_size_request (checkbutton13_C_M, 118, 24);

  checkbutton16_LD_M = gtk_check_button_new_with_mnemonic (_("Lesmiless Dance"));
  gtk_widget_show (checkbutton16_LD_M);
  gtk_fixed_put (GTK_FIXED (fixed12), checkbutton16_LD_M, 1080, 176);
  gtk_widget_set_size_request (checkbutton16_LD_M, 144, 24);

  checkbutton15_Z_M = gtk_check_button_new_with_mnemonic (_("Zoumba"));
  gtk_widget_show (checkbutton15_Z_M);
  gtk_fixed_put (GTK_FIXED (fixed12), checkbutton15_Z_M, 1080, 136);
  gtk_widget_set_size_request (checkbutton15_Z_M, 118, 24);

  checkbutton14_Y_M = gtk_check_button_new_with_mnemonic (_("Yoga"));
  gtk_widget_show (checkbutton14_Y_M);
  gtk_fixed_put (GTK_FIXED (fixed12), checkbutton14_Y_M, 1080, 96);
  gtk_widget_set_size_request (checkbutton14_Y_M, 118, 24);

  checkbutton9_BC_M = gtk_check_button_new_with_mnemonic ("Body combat");
  gtk_button_set_use_stock (GTK_BUTTON (checkbutton9_BC_M), TRUE);
  gtk_widget_show (checkbutton9_BC_M);
  gtk_fixed_put (GTK_FIXED (fixed12), checkbutton9_BC_M, 936, 48);
  gtk_widget_set_size_request (checkbutton9_BC_M, 118, 24);

  checkbutton10_BA_M = gtk_check_button_new_with_mnemonic (_("Body Attack"));
  gtk_widget_show (checkbutton10_BA_M);
  gtk_fixed_put (GTK_FIXED (fixed12), checkbutton10_BA_M, 936, 96);
  gtk_widget_set_size_request (checkbutton10_BA_M, 118, 24);

  checkbutton11_BP_M = gtk_check_button_new_with_mnemonic (_("Body Pump"));
  gtk_widget_show (checkbutton11_BP_M);
  gtk_fixed_put (GTK_FIXED (fixed12), checkbutton11_BP_M, 936, 136);
  gtk_widget_set_size_request (checkbutton11_BP_M, 118, 24);

  checkbutton12_BB_M = gtk_check_button_new_with_mnemonic (_("Body Balance"));
  gtk_widget_show (checkbutton12_BB_M);
  gtk_fixed_put (GTK_FIXED (fixed12), checkbutton12_BB_M, 936, 176);
  gtk_widget_set_size_request (checkbutton12_BB_M, 118, 24);

  label43 = gtk_label_new (_("Les cours :"));
  gtk_widget_show (label43);
  gtk_fixed_put (GTK_FIXED (fixed12), label43, 824, 40);
  gtk_widget_set_size_request (label43, 104, 32);

  label44 = gtk_label_new (_("capacit\303\251 maximale journaliere :"));
  gtk_widget_show (label44);
  gtk_fixed_put (GTK_FIXED (fixed12), label44, 784, 232);
  gtk_widget_set_size_request (label44, 224, 32);

  label61 = gtk_label_new (_("<span foreground=\"red\"font_desc=\"Arial 18\"> DONNER L'ID</span>"));
  gtk_widget_show (label61);
  gtk_fixed_put (GTK_FIXED (fixed12), label61, 560, 40);
  gtk_widget_set_size_request (label61, 177, 57);
  gtk_label_set_use_markup (GTK_LABEL (label61), TRUE);

  entryid_modifer = gtk_entry_new ();
  gtk_widget_show (entryid_modifer);
  gtk_fixed_put (GTK_FIXED (fixed12), entryid_modifer, 552, 96);
  gtk_widget_set_size_request (entryid_modifer, 200, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryid_modifer), 8226);

  button_chercher_id_M = gtk_button_new ();
  gtk_widget_show (button_chercher_id_M);
  gtk_fixed_put (GTK_FIXED (fixed12), button_chercher_id_M, 600, 144);
  gtk_widget_set_size_request (button_chercher_id_M, 106, 37);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (button_chercher_id_M), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image68 = gtk_image_new_from_stock ("gtk-find-and-replace", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image68);
  gtk_box_pack_start (GTK_BOX (hbox13), image68, FALSE, FALSE, 0);

  label62 = gtk_label_new_with_mnemonic (_("chercher"));
  gtk_widget_show (label62);
  gtk_box_pack_start (GTK_BOX (hbox13), label62, FALSE, FALSE, 0);

  button2_enregistrer_M = gtk_button_new ();
  gtk_widget_show (button2_enregistrer_M);
  gtk_fixed_put (GTK_FIXED (fixed12), button2_enregistrer_M, 544, 496);
  gtk_widget_set_size_request (button2_enregistrer_M, 184, 64);

  alignment9_enrg = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9_enrg);
  gtk_container_add (GTK_CONTAINER (button2_enregistrer_M), alignment9_enrg);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9_enrg), hbox9);

  image50 = gtk_image_new_from_stock ("gtk-save", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image50);
  gtk_box_pack_start (GTK_BOX (hbox9), image50, FALSE, FALSE, 0);

  label48_mod = gtk_label_new_with_mnemonic (_("Enregistrer"));
  gtk_widget_show (label48_mod);
  gtk_box_pack_start (GTK_BOX (hbox9), label48_mod, FALSE, FALSE, 0);

  label16_modf = gtk_label_new (_("Modifier"));
  gtk_widget_show (label16_modf);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 4), label16_modf);

  fixed11 = gtk_fixed_new ();
  gtk_widget_show (fixed11);
  gtk_container_add (GTK_CONTAINER (notebook2), fixed11);

  image29 = create_pixmap (c_b_gestion_coach_add, "553285991_4122503948018201_4707852305121133389_n.png");
  gtk_widget_show (image29);
  gtk_fixed_put (GTK_FIXED (fixed11), image29, 0, 0);
  gtk_widget_set_size_request (image29, 128, 408);

  image34 = create_pixmap (c_b_gestion_coach_add, "553285991_4122503948018201_4707852305121133389_n.png");
  gtk_widget_show (image34);
  gtk_fixed_put (GTK_FIXED (fixed11), image34, 0, 400);
  gtk_widget_set_size_request (image34, 128, 224);

  image39 = create_pixmap (c_b_gestion_coach_add, "551044963_789941773825632_1486066102389035571_n.png");
  gtk_widget_show (image39);
  gtk_fixed_put (GTK_FIXED (fixed11), image39, 1128, 0);
  gtk_widget_set_size_request (image39, 160, 408);

  image44 = create_pixmap (c_b_gestion_coach_add, "551044963_789941773825632_1486066102389035571_n.png");
  gtk_widget_show (image44);
  gtk_fixed_put (GTK_FIXED (fixed11), image44, 1128, 400);
  gtk_widget_set_size_request (image44, 160, 216);

  fixed13 = gtk_fixed_new ();
  gtk_widget_show (fixed13);
  gtk_fixed_put (GTK_FIXED (fixed11), fixed13, 0, 0);
  gtk_widget_set_size_request (fixed13, 0, 0);

  image52 = create_pixmap (c_b_gestion_coach_add, "553285991_4122503948018201_4707852305121133389_n.png");
  gtk_widget_show (image52);
  gtk_fixed_put (GTK_FIXED (fixed13), image52, 0, 0);
  gtk_widget_set_size_request (image52, 128, 408);

  image53 = create_pixmap (c_b_gestion_coach_add, "553285991_4122503948018201_4707852305121133389_n.png");
  gtk_widget_show (image53);
  gtk_fixed_put (GTK_FIXED (fixed13), image53, 0, 400);
  gtk_widget_set_size_request (image53, 128, 224);

  image54 = create_pixmap (c_b_gestion_coach_add, "551044963_789941773825632_1486066102389035571_n.png");
  gtk_widget_show (image54);
  gtk_fixed_put (GTK_FIXED (fixed13), image54, 1128, 0);
  gtk_widget_set_size_request (image54, 160, 408);

  image55 = create_pixmap (c_b_gestion_coach_add, "551044963_789941773825632_1486066102389035571_n.png");
  gtk_widget_show (image55);
  gtk_fixed_put (GTK_FIXED (fixed13), image55, 1128, 400);
  gtk_widget_set_size_request (image55, 160, 216);

  entry12_id = gtk_entry_new ();
  gtk_widget_show (entry12_id);
  gtk_fixed_put (GTK_FIXED (fixed13), entry12_id, 656, 168);
  gtk_widget_set_size_request (entry12_id, 208, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry12_id), 8226);

  label52_id = gtk_label_new (_("<span foreground=\"black\"font_desc=\"Arial 20\">DONNER L'ID </span>"));
  gtk_widget_show (label52_id);
  gtk_fixed_put (GTK_FIXED (fixed13), label52_id, 352, 160);
  gtk_widget_set_size_request (label52_id, 320, 48);
  gtk_label_set_use_markup (GTK_LABEL (label52_id), TRUE);

  button4_chercher = gtk_button_new ();
  gtk_widget_show (button4_chercher);
  gtk_fixed_put (GTK_FIXED (fixed13), button4_chercher, 544, 336);
  gtk_widget_set_size_request (button4_chercher, 184, 72);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (button4_chercher), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image56 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image56);
  gtk_box_pack_start (GTK_BOX (hbox11), image56, FALSE, FALSE, 0);

  label51_cher = gtk_label_new_with_mnemonic (_("Chercher"));
  gtk_widget_show (label51_cher);
  gtk_box_pack_start (GTK_BOX (hbox11), label51_cher, FALSE, FALSE, 0);

  label17_cher = gtk_label_new (_("Chercher"));
  gtk_widget_show (label17_cher);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook2), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook2), 5), label17_cher);

  g_signal_connect ((gpointer) button1_mdo, "clicked",
                    G_CALLBACK (on_button1_mdo_clicked),
                    NULL);
  g_signal_connect ((gpointer) button2_valider, "clicked",
                    G_CALLBACK (on_button2_valider_clicked),
                    NULL);
  g_signal_connect ((gpointer) button4_supprimer_coach, "clicked",
                    G_CALLBACK (on_button4_supprimer_coach_clicked),
                    NULL);
  g_signal_connect ((gpointer) button3_ajouter_coach, "clicked",
                    G_CALLBACK (on_button3_ajouter_coach_clicked),
                    NULL);
  g_signal_connect ((gpointer) button5_modofier_coach, "clicked",
                    G_CALLBACK (on_button5_modofier_coach_clicked),
                    NULL);
  g_signal_connect ((gpointer) button6_chercher_coach, "clicked",
                    G_CALLBACK (on_button6_chercher_coach_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobutton1_1a, "toggled",
                    G_CALLBACK (on_radiobutton1_1a_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton2_2a, "toggled",
                    G_CALLBACK (on_radiobutton2_2a_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton3_3a, "toggled",
                    G_CALLBACK (on_radiobutton3_3a_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton3_BP, "toggled",
                    G_CALLBACK (on_checkbutton3_BP_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton2_BA, "toggled",
                    G_CALLBACK (on_checkbutton2_BA_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton1_BC, "toggled",
                    G_CALLBACK (on_checkbutton1_BC_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton4_BB, "toggled",
                    G_CALLBACK (on_checkbutton4_BB_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton8_LD, "toggled",
                    G_CALLBACK (on_checkbutton8_LD_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton7_zoum, "toggled",
                    G_CALLBACK (on_checkbutton7_zoum_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton6_yoga, "toggled",
                    G_CALLBACK (on_checkbutton6_yoga_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton5_Car, "toggled",
                    G_CALLBACK (on_checkbutton5_Car_toggled),
                    NULL);
  g_signal_connect ((gpointer) button1_enregistrer_A, "clicked",
                    G_CALLBACK (on_button1_enregistrer_A_clicked),
                    NULL);
  g_signal_connect ((gpointer) button3_supp, "clicked",
                    G_CALLBACK (on_button3_supp_clicked),
                    NULL);
  g_signal_connect ((gpointer) radiobutton4_1ans_M, "toggled",
                    G_CALLBACK (on_radiobutton4_1ans_M_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton5_2ans_M, "toggled",
                    G_CALLBACK (on_radiobutton5_2ans_M_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton6_3ans_M, "toggled",
                    G_CALLBACK (on_radiobutton6_3ans_M_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton13_C_M, "toggled",
                    G_CALLBACK (on_checkbutton13_C_M_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton16_LD_M, "toggled",
                    G_CALLBACK (on_checkbutton16_LD_M_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton15_Z_M, "toggled",
                    G_CALLBACK (on_checkbutton15_Z_M_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton14_Y_M, "toggled",
                    G_CALLBACK (on_checkbutton14_Y_M_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton9_BC_M, "toggled",
                    G_CALLBACK (on_checkbutton9_BC_M_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton10_BA_M, "toggled",
                    G_CALLBACK (on_checkbutton10_BA_M_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton11_BP_M, "toggled",
                    G_CALLBACK (on_checkbutton11_BP_M_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton12_BB_M, "toggled",
                    G_CALLBACK (on_checkbutton12_BB_M_toggled),
                    NULL);
  g_signal_connect ((gpointer) button_chercher_id_M, "clicked",
                    G_CALLBACK (on_button_chercher_id_M_clicked),
                    NULL);
  g_signal_connect ((gpointer) button2_enregistrer_M, "clicked",
                    G_CALLBACK (on_button2_enregistrer_M_clicked),
                    NULL);
  g_signal_connect ((gpointer) button4_chercher, "clicked",
                    G_CALLBACK (on_button4_chercher_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (c_b_gestion_coach_add, c_b_gestion_coach_add, "c_b_gestion_coach_add");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, notebook2, "notebook2");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, entry1_id, "entry1_id");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, label20_md, "label20_md");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, entry2_md, "entry2_md");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, image19, "image19");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, image20, "image20");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, image17, "image17");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, image18, "image18");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, label18, "label18");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, label19_id, "label19_id");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, button1_mdo, "button1_mdo");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, button2_valider, "button2_valider");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, alignment3_vald, "alignment3_vald");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, image16, "image16");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, label21_vald, "label21_vald");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, label12_add, "label12_add");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, image30, "image30");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, image35, "image35");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, image40, "image40");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, image25, "image25");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, label22, "label22");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, button4_supprimer_coach, "button4_supprimer_coach");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, image22, "image22");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, label24_sup, "label24_sup");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, button3_ajouter_coach, "button3_ajouter_coach");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, alignment4_aj, "alignment4_aj");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, image21, "image21");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, label23_aj, "label23_aj");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, button5_modofier_coach, "button5_modofier_coach");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, alignment6_mod, "alignment6_mod");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, image23, "image23");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, label25_mod, "label25_mod");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, button6_chercher_coach, "button6_chercher_coach");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, alignment7_cher, "alignment7_cher");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, image24, "image24");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, label26_cher, "label26_cher");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, label13_gc, "label13_gc");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, image26, "image26");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, image31, "image31");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, image41, "image41");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, label27_nom, "label27_nom");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, entry1_nom, "entry1_nom");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, label28_pren, "label28_pren");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, entry2_pren, "entry2_pren");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, calendar1_dn, "calendar1_dn");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, label29_dn, "label29_dn");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, entry3_numtel, "entry3_numtel");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, label30_numtel, "label30_numtel");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, label31_sal, "label31_sal");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, label32_cours, "label32_cours");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, spinbutton1_cap, "spinbutton1_cap");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, image36, "image36");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, label33_cap, "label33_cap");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, label34_contr, "label34_contr");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, label35_md, "label35_md");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, entry4_md, "entry4_md");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, entry5_id, "entry5_id");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, label36_id, "label36_id");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, radiobutton1_1a, "radiobutton1_1a");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, radiobutton2_2a, "radiobutton2_2a");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, radiobutton3_3a, "radiobutton3_3a");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, checkbutton3_BP, "checkbutton3_BP");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, checkbutton2_BA, "checkbutton2_BA");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, checkbutton1_BC, "checkbutton1_BC");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, checkbutton4_BB, "checkbutton4_BB");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, checkbutton8_LD, "checkbutton8_LD");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, checkbutton7_zoum, "checkbutton7_zoum");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, checkbutton6_yoga, "checkbutton6_yoga");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, checkbutton5_Car, "checkbutton5_Car");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, comboboxentry3, "comboboxentry3");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, button1_enregistrer_A, "button1_enregistrer_A");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, alignment8_enrg, "alignment8_enrg");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, image45, "image45");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, label37, "label37");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, label14_ajouter, "label14_ajouter");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, image27, "image27");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, image32, "image32");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, image37, "image37");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, image42, "image42");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, entry11_id, "entry11_id");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, label49_id, "label49_id");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, button3_supp, "button3_supp");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, image51, "image51");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, label50, "label50");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, label15_supp, "label15_supp");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, fixed10, "fixed10");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, image28, "image28");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, image33, "image33");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, image38, "image38");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, image43, "image43");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, fixed12, "fixed12");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, image46, "image46");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, image47, "image47");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, image48, "image48");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, entry6_nom, "entry6_nom");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, label39, "label39");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, entry7_prenom, "entry7_prenom");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, calendar2, "calendar2");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, label40, "label40");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, entry8_numtel, "entry8_numtel");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, label41, "label41");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, label42, "label42");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, spinbutton2, "spinbutton2");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, image49, "image49");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, label45, "label45");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, label46, "label46");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, entry9_md_M, "entry9_md_M");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, entry10_id_M, "entry10_id_M");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, label47, "label47");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, label38, "label38");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, comboboxentry2, "comboboxentry2");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, radiobutton4_1ans_M, "radiobutton4_1ans_M");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, radiobutton5_2ans_M, "radiobutton5_2ans_M");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, radiobutton6_3ans_M, "radiobutton6_3ans_M");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, checkbutton13_C_M, "checkbutton13_C_M");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, checkbutton16_LD_M, "checkbutton16_LD_M");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, checkbutton15_Z_M, "checkbutton15_Z_M");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, checkbutton14_Y_M, "checkbutton14_Y_M");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, checkbutton9_BC_M, "checkbutton9_BC_M");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, checkbutton10_BA_M, "checkbutton10_BA_M");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, checkbutton11_BP_M, "checkbutton11_BP_M");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, checkbutton12_BB_M, "checkbutton12_BB_M");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, label43, "label43");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, label44, "label44");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, label61, "label61");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, entryid_modifer, "entryid_modifer");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, button_chercher_id_M, "button_chercher_id_M");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, image68, "image68");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, label62, "label62");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, button2_enregistrer_M, "button2_enregistrer_M");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, alignment9_enrg, "alignment9_enrg");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, image50, "image50");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, label48_mod, "label48_mod");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, label16_modf, "label16_modf");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, fixed11, "fixed11");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, image29, "image29");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, image34, "image34");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, image39, "image39");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, image44, "image44");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, fixed13, "fixed13");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, image52, "image52");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, image53, "image53");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, image54, "image54");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, image55, "image55");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, entry12_id, "entry12_id");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, label52_id, "label52_id");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, button4_chercher, "button4_chercher");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, image56, "image56");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, label51_cher, "label51_cher");
  GLADE_HOOKUP_OBJECT (c_b_gestion_coach_add, label17_cher, "label17_cher");

  return c_b_gestion_coach_add;
}

